xavier2/front/urls.py
from django.urls import path
from . import views

urlpatterns=[path('',views.main ,  name='mainpage'),
			path('logout/',views.logout_view ,  name='logout'),
			path('discussions/',views.discuss ,  name='discusspage'),
			path('discussions/main/',views.discuss_main ,  name='discussmainpage'),
			path('add/',views.add ,  name='addpage'),
			path('study/',views.study ,  name='studypage'),
			path('quiz/',views.quiz ,  name='quizpage'),
			path('sign/',views.sign ,  name='signpage')
]

xavier2/xavier2/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls'))
]

if settings.DEBUG :
	urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

xavier2/front/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import random , string

from django.conf import settings
from django.contrib.auth import get_user_model




def get_code():
	return ''.join(random.choice(string.ascii_letters+string.digits) for _ in range(8))

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class Discussion(models.Model):


	title = models.CharField(max_length=30  , default='Please help me with this')
	content = models.TextField()
	time= models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User , on_delete =  models.SET(get_sentinel_user))
	room = models.CharField(max_length=8, default=get_code)

	def __str__(self):
		return f'{self.title} : {self.content}'

	



class Comment(models.Model):
	content = models.TextField()
	time= models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User , on_delete = models.CASCADE)
	room = models.CharField(max_length=8, default='00000000')

	def __str__(self):
		return f'{self.author} : {self.content}'

		

class Material(models.Model):
	name = models.CharField(max_length=30  , default='New material')
	file = models.FileField(upload_to = 'materials')
	thumb = models.ImageField(default='ext_pics/default.png')
	tag = models.CharField(max_length=7, default=None)

	def __str__(self):
		return f'{self.name} : {self.tag}'

	

class question(models.Model):
	ques = models.TextField()
	a1 = models.CharField(max_length=50 )
	a2 = models.CharField(max_length=50 )
	a3 = models.CharField(max_length=50 )
	a4 = models.CharField(max_length=50 )
	correct = models.CharField(max_length=1 )
	course = models.CharField(max_length=9,
                choices = (('cn' , 'Computer Networks'),('os' , 'Operating System'),
                          ('dbms' , 'Database Management'),('ml' , 'Machine Learning')),
                default = 'cn' )

	def __str__(self):
		return f'{self.course} : {self.ques[:20]}....... '
	





class Profile(models.Model):
	user= models.OneToOneField(User , on_delete = models.CASCADE )
	image = models.ImageField(default='default.jpg' , upload_to = 'profile_pics')
	color = models.CharField(max_length=7, default='#000000')


	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img=Image.open(self.image.path)

		if img.height >300 or img.width > 300 :
			img.thumbnail((300,300))
			img.save(self.image.path)




class Announcement(models.Model):
	title = models.CharField(max_length=30  , default='New announcement')
	content = models.TextField()
	time= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.title} : {self.content}'

xavier2/front/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Comment , Announcement , Profile , Discussion , Material , question
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django import forms
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import  AuthenticationForm , UserCreationForm
import random



class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class SendComment(forms.ModelForm):
	class Meta :
		model = Comment
		fields = ['content' , 'room']

class NewDiscussion(forms.ModelForm):
	class Meta :
		model = Discussion
		fields = ['content' ,'title']

class NewAnnouncement(forms.ModelForm):
	class Meta :
		model = Announcement
		fields = ['content' ,'title']

class NewMaterial(forms.ModelForm):
	class Meta :
		model = Material
		fields = ['name' ,'file' ,'tag']




def main(request):

	if not(request.user.is_authenticated):
		  return redirect('signpage')


	announcements = Announcement.objects.all()[len(Announcement.objects.all())-20:
					] if len(Announcement.objects.all()) > 21 else Announcement.objects.all()

	announcements2 = []
	

	for i in range(len(announcements)-1 , -1 , -1):
		announcements2.append(announcements[i])




	return render(request, 'front/main.html' , {'announcements' : announcements2})






def discuss(request):

	if not(request.user.is_authenticated):
		  return redirect('signpage')

	discussion = Discussion.objects.all()[len(Discussion.objects.all())-20:
					] if len(Discussion.objects.all()) > 21 else Discussion.objects.all()

	discussion2 = []
	

	for i in range(len(discussion)-1 , -1 , -1):
		discussion2.append(discussion[i])

	



	return render(request, 'front/disc.html' , {'discussions' : discussion2})





def quiz(request ):
	if not(request.user.is_authenticated):
		return redirect('signpage')

	if request.method == 'POST':

		if request.POST['action']=='start':


			try:
				course=request.POST['course']
			except:
				course = None

			if course == None :
				ques = question.objects.all()
			else :
				ques = question.objects.filter(course=course)



			ques2=[]
			while len(ques2)<5:
				q= random.choice(ques)
				if q not in ques2 :
					ques2.append(q)


			return render(request , 'front/mcq.html' , {'ques' : ques2 })

		if request.POST['action']=='submit':
			ids=[]
			ans=[]
			
			for i in range(5):
				ids.append(request.POST.get(f'a{i+1}').split(':')[0]) 
				try :
					ans.append(request.POST.get(f'a{i+1}').split(':')[-1][-1]) 
				except :
					ans.append('x')



						

			score = 0
			ques=[]
			
			for i in range(len(ids)) :
				q= question.objects.filter(id=ids[i])[0]
				ques.append(q)
				if q.correct == ans[i] :
					score+=1
				
					
		
			return render(request , 'front/quizend.html' , {'score' : score , 'ques' : ques , 'ans' : ans})




				
			





	return render(request , 'front/quizstart.html')










def study(request) :
	if not(request.user.is_authenticated):
		return redirect('signpage')




	try:
		tag=request.GET['tag']
	except:
		tag = None

	if tag == None :
		study = Material.objects.all()
	else :
		study = Material.objects.filter(tag=tag)
	

	study2 = []
	

	for i in range(len(study)-1 , -1 , -1):
		study2.append(study[i])

	
	empty = True if len(study2)==0 else False




	return render(request , 'front/study.html' ,  { 'study' : study2 , 'empty' :empty })



def add(request) :
	if not(request.user.is_authenticated):
		return redirect('signpage')


	if request.method == 'POST':

		
		
		if request.POST['action']=='announce':
			send = NewAnnouncement(request.POST)
			if send.is_valid() :
				
				if request.user.is_staff :
					Announcement.objects.create(
				 						content=send.cleaned_data['content'] ,
				 						title=send.cleaned_data['title'])
				print('Announcement')
				
		if request.POST['action']=='discuss':
			send = NewDiscussion(request.POST)
			if send.is_valid() :
				print(request.POST)
				
			
				Discussion.objects.create(author=request.user ,
				 						content=send.cleaned_data['content'] ,
				 						title=send.cleaned_data['title'])

		if request.POST['action']=='study':
			form = NewMaterial(request.POST , request.FILES)
			if form.is_valid() :
				form.save()


			
	send = NewDiscussion()
	send2= NewMaterial()





	return render(request , 'front/add.html' , {'send' : send , 'send2' : send2 })
















def discuss_main(request) :
	if not(request.user.is_authenticated):
		return redirect('signpage')



	if request.method == 'POST':

		send = SendComment(request.POST )
		
		if send.is_valid():
			
			Comment.objects.create(author=request.user ,
			 						content=send.cleaned_data['content'] ,
			 						room=send.cleaned_data['room'])
			
			print('commented ')


	try:
		discuss=request.GET['discuss']
	except:
		return HttpResponse('<h1>No such discussion</h1>')

	discussion = Discussion.objects.filter(room=discuss)[0]
	comments = Comment.objects.filter(room=discussion.room)
	
	comments2 = []
	

	for i in range(len(comments)-1 , -1 , -1):
		comments2.append(comments[i])


	send = SendComment()

	return render(request, 'front/disc_main.html' , {'discussion' : discussion , 'comments' :comments2 , 'send' : send })








def sign(request):

    if request.method == 'GET':
        form1 = AuthenticationForm()
        form2 = UserCreationForm()
        return render(request, 'front/sign.html', {'form1' : form1 , 'form2' : form2 })

    if request.method == 'POST':

        if request.POST['action'] == 'login':
        	form1 = AuthenticationForm(request=request, data=request.POST)
        	form2 = UserCreationForm()
        	if form1.is_valid():
        	    username = form1.cleaned_data.get('username')
        	    password = form1.cleaned_data.get('password')
        	    user = authenticate(username=username, password=password)
        	    if user is not None:
        	        login(request, user)
        	        return redirect('mainpage')
        	    else:
        	        form1.error_messages['nouser']= _('No such user found')
        	        raise forms.ValidationError(
        	        form1.error_messages['nouser'],
        	        code='nouser',)
        	        return render(request, 'front/sign.html', {'form1' : form1 , 'form2' : form2 })
        	else:
        	    
        	    return render(request, 'front/sign.html', {'form1' : form1 , 'form2' : form2 }) 


        if request.POST['action'] == 'signup':
        	form1 = AuthenticationForm()
        	form2 = UserCreationForm(request.POST)
        	if form2.is_valid():
        	    form2.save()
        	    return redirect('signpage')

        	else:
        	    return render(request, 'front/sign.html', {'form1' : form1 , 'form2' : form2 }) 



  

    



@login_required
def logout_view(request):
    logout(request)
    return redirect('mainpage')

xavier2/front/templates/front/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href='{% static "front/navbar.css" %}' />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
    />
    <link rel="stylesheet" href='{% static "front/NewPost.css" %}' />
    <style type="text/css">
      label {display: none;}
    </style>
    <title>Add new post</title>
  </head>
  <body>
    <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
      <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
          <div class="sidebar-brand">
            <a href="{% url 'mainpage' %} " >Xavier</a>
            <div id="close-sidebar">
              <i class="fas fa-times"></i>
            </div>
          </div>
          <div class="sidebar-header">
            <div class="user-pic">
              <img
                class="img-responsive img-rounded"
                src="{{request.user.profile.image.url}}"
                alt="User picture"
                style = "border-radius: 50% ;"
              />
            </div>
            <div class="user-info">
              <span class="user-name">
                {{ request.user.username }}
              </span>
              <span class="user-role">
                  {% if request.user.is_superuser %}
              Superuser
                 
                 {% elif request.user.is_staff %}
              Staff
                  {% else %}
              Student
                  {% endif %}

            </span>
              <span class="user-status">
                <i class="fa fa-circle"></i>
                <span>Online</span>
              </span>

            </div>
          </div>



          <!-- sidebar-search  -->
          <div class="sidebar-menu">
            <ul>
              <li>
                <a href="{% url 'mainpage' %} " 
                  ><i class="fa fa-home" aria-hidden="true"></i>
                  <span>Announcements</span>
                </a>
              </li>
              <li>
                <a href="{% url 'discusspage' %} "  >
                  <i class="fas  fa-comments"></i>
                  <span>Discussions</span>
                </a>
              </li>

              <li>
                <a href="{% url 'studypage' %}"
                  ><i class="fa  fa-book"></i>
                  <span>Study Material</span>
                </a>
              </li>
              <li>
                <a href="{% url 'quizpage' %} "
                ><i class="fa fa-calendar"></i>
                  <span>Quiz</span>
                </a>
              </li>
              <li>
                <a href="{% url 'addpage' %} " style="color: white" 
                  ><i class="fas fa-plus"  aria-hidden="true"></i>
                  <span>Add</span>
                </a>
              </li>
            </ul>
          </div>
          <!-- sidebar-menu  -->
          <div class="sidebar-footer">
            <a href="{% url 'logout' %} " style="text-decoration: none">
              <i class="fa fa-power-off"></i>
              <span>Logout</span></a
            >
          </div>
        </div>
        <!-- sidebar-content  -->
      </nav>
      <!-- sidebar-wrapper  -->
      <main class="page-content">
        <div class="container">
          <div class="newPost">
            <h3>Add New Post</h3>
            <input type="text" placeholder="Enter title here" id='title' value="Please help me with this" />
            <div class="toolbar">
              <button type="button" data-func="bold">
                <i class="fa fa-bold"></i>
              </button>
              <button type="button" data-func="italic">
                <i class="fa fa-italic"></i>
              </button>
              <button type="button" data-func="underline">
                <i class="fa fa-underline"></i>
              </button>
              <button type="button" data-func="justifyleft">
                <i class="fa fa-align-left"></i>
              </button>
              <button type="button" data-func="justifycenter">
                <i class="fa fa-align-center"></i>
              </button>
              <button type="button" data-func="justifyright">
                <i class="fa fa-align-right"></i>
              </button>
              <button type="button" data-func="insertunorderedlist">
                <i class="fa fa-list-ul"></i>
              </button>
              <button type="button" data-func="insertorderedlist">
                <i class="fa fa-list-ol"></i>
              </button>
              <div class="customSelect">
                <select data-func="fontname">
                  <optgroup label="Serif Fonts">
                    <option value="Bree Serif">Bree Serif</option>
                    <option value="Georgia">Georgia</option>
                    <option value="Palatino Linotype">Palatino Linotype</option>
                    <option value="Times New Roman">Times New Roman</option>
                  </optgroup>
                  <optgroup label="Sans Serif Fonts">
                    <option value="Arial">Arial</option>
                    <option value="Arial Black">Arial Black</option>
                    <option value="Asap" selected>Asap</option>
                    <option value="Comic Sans MS">Comic Sans MS</option>
                    <option value="Impact">Impact</option>
                    <option value="Lucida Sans Unicode">
                      Lucida Sans Unicode
                    </option>
                    <option value="Tahoma">Tahoma</option>
                    <option value="Trebuchet MS">Trebuchet MS</option>
                    <option value="Verdana">Verdana</option>
                  </optgroup>
                  <optgroup label="Monospace Fonts">
                    <option value="Courier New">Courier New</option>
                    <option value="Lucida Console">Lucida Console</option>
                  </optgroup>
                </select>
              </div>
              <div class="customSelect">
                <select id='type' data-func="formatblock" onchange ="change(event)">
                  <option value="discuss" >Discussion</option>
                  {% if request.user.is_staff %}
                  <option value="announce" >Announcement</option>
                  {% endif %} 
                  <option value="study">Study material</option>
                </select>
              </div>
            </div>
            <div class="editor" contenteditable id="text"></div> <br>
            <form  enctype="multipart/form-data" id="study" method="post" style="display: none; padding-bottom: 1rem ; ">{% csrf_token %}
                       {{send2}}
                    <button type="submit" style="display: none;" name='action' value='study' id="send2" >Send</button> 
            </form>
            <div class="buttons">
              <!--<button type="button">save draft</button>-->
              <button id="button" onclick = 'add(event)' ></button>
            </div>
            <form method="post" style="display: none;">{% csrf_token %}
                       {{send}}
                    <button type="submit" name='action' value='discuss' id="send" >Send</button> 
                  </form>

            
          </div>
        </div>
      </main>
      <!-- page-content" -->
    </div>
    <!-- page-wrapper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/esm/popper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.js"></script>
       <script >
      $(".sidebar-dropdown > a").click(function() {
    $(".sidebar-submenu").slideUp(200);
    if (
      $(this)
        .parent()
        .hasClass("active")
    ) {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .parent()
        .removeClass("active");
    } else {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .next(".sidebar-submenu")
        .slideDown(200);
      $(this)
        .parent()
        .addClass("active");
    }
  });
  
  $("#close-sidebar").click(function() {
    $(".page-wrapper").removeClass("toggled");
  });
  $("#show-sidebar").click(function() {
    $(".page-wrapper").addClass("toggled");
  });
  

document.querySelector('#id_tag').placeholder = 'tag'
    document.querySelector('#id_name').style.display='none'




  function add(e){
 
    if (document.querySelector('#type').value=='study'){

    document.querySelector('#id_name').value=document.querySelector('#title').value


    document.querySelector('#send2').click()}

   else {
    document.querySelector('#id_content').value = document.querySelector('#text').innerText ;
    document.querySelector('#id_title').value = document.querySelector('#title').value ;
    document.querySelector('#send').value=document.querySelector('#type').value

    document.querySelector('#send').click() }


  }

  function change(e){
    if (document.querySelector('#type').value=='discuss'){
    document.querySelector('#title').value='Please help me with this'
    document.querySelector('#study').style.display='none'  
    document.querySelector('#text').style.display='' 
  }
  if (document.querySelector('#type').value=='announce'){
    document.querySelector('#title').value='New Announcement' 
    document.querySelector('#study').style.display='none'  
    document.querySelector('#text').style.display='' 
  } 
    if (document.querySelector('#type').value=='study'){
    document.querySelector('#title').value='New material'  
    document.querySelector('#study').style.display=''  
    document.querySelector('#text').style.display='none'  
 } 
  
  }

 


  
    </script>
  </body>
</html>

xavier2/front/templates/front/disc_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href='{% static "front/navbar.css" %}' />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
    />
    <link rel="stylesheet" href='{% static "front/material.css" %}' />
    <link rel="stylesheet" href='{% static "front/study.css" %}' />
    <style>
    	#id_room { display: none; }
      body {
        margin-top: 20px;
        background: #eee;
      }
      @media (min-width: 0) {
        .g-mr-15 {
          margin-right: 1.07143rem !important;
        }
      }
      @media (min-width: 0) {
        .g-mt-3 {
          margin-top: 0.21429rem !important;
        }
      }

      .g-height-50 {
        height: 50px;
      }

      .g-width-50 {
        width: 50px !important;
      }

      @media (min-width: 0) {
        .g-pa-30 {
          padding: 2.14286rem !important;
        }
      }

      .g-bg-secondary {
        background-color: #fafafa !important;
      }

      .u-shadow-v18 {
        box-shadow: 0 5px 10px -6px rgba(0, 0, 0, 0.15);
      }

      .g-color-gray-dark-v4 {
        color: #777 !important;
      }

      .g-font-size-12 {
        font-size: 0.85714rem !important;
      }

      .media-comment {
        margin-top: 20px;
      }

      label { display: none; }
    </style>
      <title>{{discussion.title}}</title>
  </head>
  <body  >
    <div class="page-wrapper chiller-theme toggled">
      <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
      </a>
      <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
          <div class="sidebar-brand">
            <a href="{% url 'mainpage' %} " >Xavier</a>
            <div id="close-sidebar">
              <i class="fas fa-times"></i>
            </div>
          </div>
          <div class="sidebar-header">
            <div class="user-pic">
              <img
                class="img-responsive img-rounded"
                src="{{request.user.profile.image.url}}"
                alt="User picture"
                style = "border-radius: 50% ;"
              />
            </div>
            <div class="user-info">
              <span class="user-name">
                {{ request.user.username }}
              </span>
              <span class="user-role">
                  {% if request.user.is_superuser %}
              Superuser
                 
                 {% elif request.user.is_staff %}
              Staff
                  {% else %}
              Student
                  {% endif %}

            </span>
              <span class="user-status">
                <i class="fa fa-circle"></i>
                <span>Online</span>
              </span>

            </div>
          </div>



          <!-- sidebar-search  -->
          <div class="sidebar-menu">
            <ul>
              <li>
                <a href="{% url 'mainpage' %} " 
                  ><i class="fa fa-home" aria-hidden="true"></i>
                  <span>Announcements</span>
                </a>
              </li>
              <li>
                <a href="{% url 'discusspage' %} "  style="color: white" >
                  <i class="fas  fa-comments"></i>
                  <span>Discussions</span>
                </a>
              </li>

              <li>
                <a href="{% url 'studypage' %}"
                  ><i class="fa  fa-book"></i>
                  <span>Study Material</span>
                </a>
              </li>
              <li>
                <a href="{% url 'quizpage' %} "
                ><i class="fa fa-calendar"></i>
                  <span>Quiz</span>
                </a>
              </li>
              <li>
                <a href="{% url 'addpage' %} " 
                ><i class="fa fa-plus" aria-hidden="true"></i>
                  <span>Add</span>
                </a>
              </li>
            </ul>
          </div>
          <!-- sidebar-menu  -->
          <div class="sidebar-footer">
            <a href="{% url 'logout' %} " style="text-decoration: none">
              <i class="fa fa-power-off"></i>
              <span>Logout</span></a
            >
          </div>
        </div>
        <!-- sidebar-content  -->
      </nav>
      <!-- sidebar-wrapper  -->
      <main class="page-content">
        <div class="container">
          <h1>{{discussion.title}}</h1> <h7 style="color: {{discussion.author.profile.color}}">{{discussion.author}}  </h7> <small> , {{discussion.time}}</small>
          <p>
            {{discussion.content}}
          </p>
          <hr />
          <h5>Comments</h5>
          <!-- comments random -->
          <link
            href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            rel="stylesheet"
            integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous"
          />
          <div class="container">
            <div class="row">
             
              {% for comment in comments %}

              <div class="col-md-8">
                <div class="media g-mb-30 media-comment">
                  <img
                    class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15"
                    src="{{comment.author.profile.image.url}}"
                    alt="Image Description"
                  />
                  <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                    <div class="g-mb-15">
                      <h5 class="h5 g-color-gray-dark-v1 mb-0" style="color: {{comment.author.profile.color}}">{{comment.author}}</h5>
                      <span class="g-color-gray-dark-v4 g-font-size-12"
                        >{{comment.time}}</span
                      >
                    </div>

                    <p>
                      {{comment.content}}
                    </p>

                  </div>
                </div>
              </div>

              {% endfor %}


            </div>
          </div>
          <!-- end-->
          <!--add comment section-->
          <div style="margin-top: 35px">
            <div style="display: flex; justify-content: center">
              <div class="col-10">
                <div class="comment-box ml-2">
                  <h6>Add a comment</h6>
                  <div class="comment-area">
                    <textarea
                    id = "text"
                      class="form-control"
                      placeholder="what is your view?"
                      rows="4"
                      

                    ></textarea>
                  </div>
                  <form method="post" style="display: none;">{% csrf_token %}
                       {{send}}
                    <button type="submit" name='action' value='sending' id="send" >Send</button>   
                    
            	</form>
                  <div class="comment-btns mt-2">
                    <div class="row">
                      <div class="col-6">
                        <div class="pull-right">
                        	
                        		
	                          <button class="btn btn-success send btn-sm" type="submit" id="send2" onclick = 'comment(event)'>
	                            Send <i class="fa fa-long-arrow-right ml-1"></i>
	                          </button>
	                        

                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <!-- page-wrapper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/esm/popper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.js"></script>
       <script >
      $(".sidebar-dropdown > a").click(function() {
    $(".sidebar-submenu").slideUp(200);
    if (
      $(this)
        .parent()
        .hasClass("active")
    ) {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .parent()
        .removeClass("active");
    } else {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .next(".sidebar-submenu")
        .slideDown(200);
      $(this)
        .parent()
        .addClass("active");
    }
  });
  
  $("#close-sidebar").click(function() {
    $(".page-wrapper").removeClass("toggled");
  });
  $("#show-sidebar").click(function() {
    $(".page-wrapper").addClass("toggled");
  });




  function comment(e){
  	console.log('hi')

  	document.querySelector('#id_room').value = '{{discussion.room}}' ;
  	document.querySelector('#id_content').value = document.querySelector('#text').value ;

  	document.querySelector('#send').click()


  }
  
  
    </script>
  </body>
</html>